global:
  appVersion: ""
  imgPath: ""


name:
replicas:
revisionHistoryLimit:

serviceMetaData:
  cluster:
  service_name:

istioEnabled: false
canaryEnabled: false

container:
  port: 8080
  path: /
  image:
    pullPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1000
      runAsGroup: 1000
  command: ["/bin/sh"]
  args: []
  livenessProbe:
    path: actuator/health
    initialDelaySeconds: 300
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 5
  readinessProbe:
    path: actuator/health
    initialDelaySeconds: 300
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 5
  startupProbe:
    path: actuator/health
    initialDelaySeconds: 300
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 5
  resources:
    cpu:
      limits:
      request:
    memory:
      limits:
      request:
  gateway:
    enabled: false
    annotations: {}
    tlsEnabled: false
    tlsIsProduction: false
    ingressClass: "nginx"
    host: "administrabien.cl"
    contextBasePath: /
    pathType: "prefix"
  virtualService:
    enabled: false
    hosts: []
    gateway:
    uriPrefix: /
    uriReWrite:
  sa:
    autoMountSAToken: false
    enforceMountableSecrets: false
  envs:

  tolerations: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 95
  targetMemoryUtilizationPercentage: 95
  averageRequestPerSeconds: 1000m