{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-configmap
data:
  # Opción A: Si quieres que el archivo properties sea una sola entrada (típico en Spring Boot)
  application.properties: |
    {{- .Values.configmap.applicationProperties | default "" | nindent 4 }}
{{- end }}