apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: "istio-ingress"
  name: "{{ .Values.name }}-gateway"
spec:
  selector:
    istio: {{ .Values.virtualService.selectorIstio }} # Esto conecta con el LoadBalancer real de AWS/Istio
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.virtualService.hosts }}
        - {{ . }}
        {{- end }}