{{ if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.name }}
  name: "{{ .Values.name }}-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.name }}-deployment"
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if and .Values.container.resources.cpu.limits  .Values.container.resources.cpu.request }}
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- end }}
  {{- if and .Values.container.resources.memory.limits  .Values.container.resources.memory.request }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- end }}

  {{- if .Values.autoscaling.averageRequestPerSeconds }}
    - type: Object
      object:
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: "{{ .Values.name }}-deployment"
        metric:
          name: istio_requests_per_second
        target:
          type: Value
          value: {{ .Values.autoscaling.averageRequestPerSeconds }}
  {{- end }}
{{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # Espera 5 minutos antes de empezar a borrar pods
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0 # Escala hacia arriba inmediatamente
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15