apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.name }}
  name: "{{ .Values.name }}-ingress"
  annotations:
    # Si usas NGINX Ingress Controller:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.container.gateway.ingressClass }} # O el nombre de tu clase (alb, nginx, etc)
  rules:
    - host: {{ .Values.container.gateway.host }}
      http:
        paths:
          - path: {{ .Values.container.gateway.contextBasePath }}
            pathType: {{ .Values.container.gateway.pathType }}
            backend:
              service:
                name: "{{ .Values.name }}-svc" # <--- [B] TIENE QUE SER EL NOMBRE DEL SERVICE
                port:
                  number: {{ .Values.container.port }}     # <--- [C] TIENE QUE SER EL 'port' DEL SERVICE