{{- if .Values.container.gateway.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.name }}
  name: "{{ .Values.name }}-ingress"
  annotations:
    # Si usas NGINX Ingress Controller:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.container.gateway.tlsIsProduction}}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- else }}
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    {{- end }}
    {{- range $key, $val := .Values.container.gateway.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.container.gateway.ingressClass }} # O el nombre de tu clase (alb, nginx, etc)
  {{- if .Values.container.gateway.tlsEnabled }}
  tls:
    - hosts:
      - {{ .Values.container.gateway.host | quote }}
      {{- if .Values.container.gateway.tlsIsProduction}}
      secretName: "{{ .Values.name }}-tls-prod-secret"
      {{- else }}
      secretName: "{{ .Values.name }}-tls-staging-secret"
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.container.gateway.host | quote }}
      http:
        paths:
          - path: {{ .Values.container.gateway.contextBasePath }}
            pathType: {{ .Values.container.gateway.pathType }}
            backend:
              service:
                name: "{{ .Values.name }}-svc" # <--- [B] TIENE QUE SER EL NOMBRE DEL SERVICE
                port:
                  number: {{ .Values.container.port }}     # <--- [C] TIENE QUE SER EL 'port' DEL SERVICE
{{- end }}