apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.name }}
  labels:
    {{- if.Values.istioEnabled }}
    istio-injection: enabled
    {{- end }}
    {{- if.Values.canaryEnabled }}
    istio.io/rev: canary
    {{- end }}