{{- if .Values.container.envs }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.name }}
  name: "{{ .Values.name }}-secret"
type: Opaque
stringData:
  {{- include "envs" . | nindent 2 }}
{{- end }}