apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: "{{ .Values.name }}-secret-store"
  namespace: "{{ .Values.name }}"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          # El rol que creaste anteriormente en Vault
          role: "{{ .Values.container.vaultRoleName }}"
          mountPath: "kubernetes"
          serviceAccountRef:
            name: "{{ .Values.container.sa.name }}"
            #audience: "https://kubernetes.default.svc.cluster.local"