apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.ms.name }}
  name: "{{ .Values.ms.name }}-secret"
type: Opaque
data:
  {{- range $key, $val := .Values.ms.container.envs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}