{{- if .Values.container.envs }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.name }}
  name: "{{ .Values.name }}-secret"
type: Opaque
stringData:
  {{- range $key, $val := base.envs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}