apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.name }}
  name: "{{ .Values.name }}-svc"
spec:
  type: ClusterIP   # Para Ingress, basta con ClusterIP (no necesitas NodePort)
  selector:
    app: "{{ .Values.name }}-label" # <--- [A] CONECTA CON EL DEPLOYMENT (Misma etiqueta)
  ports:
    - port: {{ .Values.container.port }}        # <--- [C] PUERTO DEL SERVICIO (Al que apuntarÃ¡ el Ingress)
      targetPort: {{ .Values.container.port }}  # Puerto del contenedor (Paso 1)