apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "{{ .Values.container.sa.enforceMountableSecrets }}"
  name: {{ .Values.name  }}-sa
  namespace: {{ .Values.name }}
secrets:
  - name: {{ .Values.name }}-secret
imagePullSecrets:
  - name: {{ .Values.name }}-image-pull-secret