apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mi-frontend-vs
spec:
  hosts:
    {{- range .Values.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  gateways:
    - "{{ .Values.name }}-gateway"
  http:
    - match:
      - uri:
        prefix: {{ .Values.virtualService.uriPrefix }}
      route:
        - destination:
          host: "{{ .Values.name }}-svc"
          port:
            number: 80