apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  namespace: {{ .Values.name }}
  name: "{{ .Values.name }}-virtualservice"
spec:
  hosts:
    - "bookinfo.com"
  gateways:
    - mygateway
  http:
    - match:
      - uri:
          prefix: {{ .Values.virtualService.uriPrefix }}
      route:
        - destination:
            host: "{{ .Values.name }}-svc"
            port:
              number: 80