apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  namespace: {{ .Values.name }}
  name: "{{ .Values.name }}-virtualservice"
spec:
  hosts:
    {{- range .Values.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  gateways:
    - "{{ .Values.name }}-gateway"
  http:
    - match:
      - uri:
          prefix: {{ .Values.virtualService.uriPrefix }}
      route:
      - destination:
          host: "{{ .Values.name }}.{{ .Values.name }}.svc.cluster.local"
          subset: v1