{{- if .Values.container.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ .Values.name }}
  name: "{{ .Values.name }}-virtualservice"
spec:
  hosts:
    {{- range .Values.container.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  gateways:
    - {{ .Values.container.virtualService.gateway }}
  http:
    - match:
      - uri:
          prefix: {{ .Values.container.virtualService.uriPrefix }}
      route:
        - destination:
            host: "{{ .Values.name }}-svc.{{ .Values.name }}.svc.cluster.local"
            port:
              number: {{ .Values.container.port }}
{{- end }}